name: 'Dispatch: Promote Release'

on:
  workflow_dispatch:
    inputs:
      target_tag:
        description: 'Version to promote'
        required: true

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Verify input version is prerelease
        run: |
          if [[ "${{ github.event.inputs.target_tag }}" != *"pre"* ]]; then
              echo "Version must be a prerelease"
              exit 1
          fi

  github_release:
    needs: check_version
    uses: ./.github/workflows/call.github_release.yml
    secrets: inherit
    with:
      release_mode: promote
      promote_from: ${{ github.event.inputs.target_tag }}
