name: 'Generic: GitHub Release'

on:
  workflow_call:
    inputs:
      release_mode:
        description: 'Release mode'
        required: true
        type: string
      version_bump:
        description: 'Version bump'
        required: false
        type: string
      promote_from:
        description: 'Promote from'
        required: false
        type: string
    outputs:
      release_created:
        description: 'Release created'
        value: ${{ jobs.github_release.outputs.release_created }}
      tag_name:
        description: 'Tag name'
        value: ${{ jobs.github_release.outputs.tag_name }}

jobs:
  github_release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Echo inputs
        run: |
          echo "release_mode: ${{ inputs.release_mode }}"
          echo "version_bump: ${{ inputs.version_bump }}"
          echo "promote_from: ${{ inputs.promote_from }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.promote_from }}

      - name: Create release
        id: release
        uses: benwoo1110/semantic-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_mode: ${{ inputs.release_mode }}
          version_bump: ${{ inputs.version_bump }}
          promote_from: ${{ inputs.promote_from }}

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Build and test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        if: steps.release.outputs.release_created == 'true'
        uses: gradle/gradle-build-action@v3
        with:
          arguments: >
            publish -x test
              -PdumptruckmanReleasesUsername=${{ secrets.REPOSILITE_REPO_USERNAME }}
              -PdumptruckmanReleasesPassword=${{ secrets.REPOSILITE_REPO_PASSWORD }}
              -PdumptruckmanSnapshotsUsername=${{ secrets.REPOSILITE_REPO_USERNAME }}
              -PdumptruckmanSnapshotsPassword=${{ secrets.REPOSILITE_REPO_PASSWORD }}
        env:
          GITHUB_VERSION: ${{ steps.release.outputs.publish_version }}

      - name: Upload release artifact
        if: steps.release.outputs.release_created == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "**/build/libs/*-${{ steps.release.outputs.publish_version }}.jar"
          file_glob: true
          tag: ${{ steps.release.outputs.tag_name }}
